language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - extra-android-m2repository
  - android-25
jdk:
- oraclejdk8
script:
- "./gradlew assembleRelease"
after_success:
- ".buildscript/deploy_snapshot.sh"
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
  - "$HOME/.m2"
env:
  global:
  - secure: QRzPxKYwSSryioZZzwZ9KZf/HnSFudDweat6vPp57GGuz5VFNSyp9goL6s7LedHTChL9KTwjWW7NEe2XbBa1SSBiNpgSofdXcDFuBB3F6XzvFDgBqq36jIlc9S6ldOWg/H7lHZPzXNEa/P8fiAtn5HDUaKwvSfP6v271phKppan8H/la1V8dfKn8f8BplnYo2oLGW5TCvMYWsER8yg4WFJyy1uWDvIcmE7VUd00dj8EpDfZCnyczWHMKnz+VZnobaQvec6au6eA1+jFxmVxO5swY5xwCsXZNoqq5PzS97Ut9JLveNmtWsZPfeFvTXS9XWAojxtrKEHp4N5sxFHQOdeYu4Cx/Pjme46vgraE2ZrprJuiPfX+UeCyhVWRumX52uWwG+lIFCObyZ+wEu2+n7mJY50sgD1xkP7S4jbydnj0gad/MckWaDOr4GLHy7sPEJ9iDdKa2HhkTBEqrtKgqywsf0wMWJAfOZokiV7iC0FCqoa/6kvo5V7tMlwWIJDNu+5YPLe2seK6fYRmBAOAwbrWmQtFZNrn0ZOMatPr1O9qW4ExAKwlL+YYurf3PbNoQ2gJ2xNrii1Vp8rlyLlauvdBqovOIgT400snMJyFutdQpbcskSWvN3E5i6MeR/TDgCwM6ep1eLnVTm0sJrGeuP2qgdlpL+VQzbYxIo6RRz4o=
  - secure: LODvB3y3sn2JvlGRS9YNQt2WwyBrfNWqnFBDaAM1Piz4FZT1wtZjaZq3RcRaSUTO1MdUJk7rJw1BZ9ATvg/89sA11zrVlS9mV8S/9Upw4vJurQ9MOLv4oPHpsHmbsLxS/re4wwMBR3H+2IHq8vfUz6e6APlRdM01S26MfCwoQSBXmKGHIxQcjRyUIiWhaRfn3xoYny6rDnW9gmmx0H3B/xTyW/G+srQS9PHcXe4J6wd39nLY9PL+1wNP2nJK/oOxRXeNN7RPUjNMX0lk7NImvL+NZmeiFrsqNydSuhqcW4de54w/DDodu4wFnKBsWbty0uStMZWJwQK9nHEnKFljJNEz71qLLLy8t+dERoJU6ZjAS+a+cRlUfbmhWh4aDkCI02MfXhGBb6jZ2GFbRzNYdUp0wmtbybLvSGoG5iq65/nGlIMCUhtoGc+sTrlh7WZTKRzUUIj6QcxxHMRGEPvXY3ebFr7D18wceTgvBsa2Oye2KKf4AUl3SmWj+Q/amtimd6MA32hoPFqJx7700mX2V8O2z3wsVAzzpytU3h1eo3MHyEQiwe6Lk9P5MWtzOkzqIq1d9iRsg6eeAKXL09FBsDkGHFn7dNFEqWd8tFbv444Borx7Vg3R6hVEOMLH2AECGkzmG4W1gNeADTxJIN03ovLp8xx6JKdafHz72fFuoBA=
