language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - extra-android-m2repository
  - android-25
jdk:
- oraclejdk8
before_script:
  - bash buildscript/test.sh
script:
- "./gradlew uploadArchives"
after_success:
- ".buildscript/deploy_snapshot.sh"
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
  - "$HOME/.m2"
env:
  global:
    - secure: oTRD70hXEwRXRqzmtQqzz0huApMfy6pi6OYy0iRN9w8LRcF6E668FmhflLNx7tM51kVFSHfQCy7RSr2NkxLDQIYqntuww/qboQIgyD8bZKxogO0xHamCA5YPfpNekmtGB6oBuOUSUTS/9alXBGAXDZrLIJEBINBVDoEp/5B0biorcA/zv4AWfS5JawHZrGmOFQlYLmP97PW1HozqxPMSH80Eg1LnxmlDD6YNxSPJCVS8N16nP2sgR0DL85cuMbpkvfwQOwssWzqSMSVC2EOEMWE1PdZYHoqjxEVfLQKUodJXOHlY4e1AYdCrFQhP7Fyyc9jCmMVwjrvkW5UliQcj1vnsLmFjH2PIb5tuJDnrur37luzPyl89v3gYfSCWDlzLjHVMu/CkR9klXtnsvZsH+Vp1Welcp3WtYj0Xvo9NqJphUEk3s4KGpS1cRDBNaFnT4qXL7Z7r4JEbLF6mVM8LVJJE65iAUJ85Lz90Qijad8fZHfXL6jfwY8TDSLjp8tzEYs7itEBbEj8FKMFfIdm9oDB2Bov1mk2/n/4YeyRSTZk4K0M7EI7smmTNvSD628+V8o2SpwveCq5PQ1FXef83hfeOlfUwPsIxR5sk9Aq/C3Nhu3O8buMAfxBqgdsaw0kc5wkBwDZe40u+YywyGwI/DxyqNPwtyOmXfKTIq9LByV4=
    - secure: fnT2KmTJ3Kjx5EhPpZ56hd1mjtn7LqFkatCT/miJrKnoXkAB9aoS9mqn7HDxHH555g9Nvf9M1g9A45VuV1amAtlZjkITEQiiwq7nRwhLL7oUdPZefvIucbrc2o/nCk4ElID0pW99VW2dbUZmbSw9b6Z0t24QKRHqVpnvVd7QFMgYuxzXKtW39wPNHnSKU1ykxb+SHaKspGi/2wbWumARcHu/RHKGWdtCNDdZ8y8YokOl4HW5bv4i1oSsdZSgSPJspNrN7N45VxCgXrI8jxDJiUchGBkXUAlQoWo5WIjBn7ZNE24d5A+EkyvkgIBhStOucvYgqJkJaDvtGcWj42ZVKowUT5kMeL5fqpz3y813rCJEP3n7T4n6Pkh2lrVY1lh+zYyltr1oFkwf0leGyIcxbzCHo9NBCvf1unAM8aEH0gTC7Doymq76CmUH+Jcn6Pc6/rE670MOZWu371AyRTFJLEHzQxHiO+6Xmp+n/Sa2XfNVUAVAtAauApUqg0cWe9XSNXK6ncpuyzOEjt3HIzmnxhnmBURuHUucMnL6iNSm7NqsVfb9Qb98YvJkQBhU3rD9vzeqopnfPdkeOyLz7agGgKTLWFxUIqIVPjccr/RCLOTJTwfELAmvuOoob9bzLode6cBsF1v3xW3ZPKOQ8KwHnOpiLflXOf0z9iD/n9HGJP8=
    - secure: kJXKrlCF/QK1v40ZVlm/ZyfFODB5g63uRDwXE419prhPW6wHFuEYhY43fJSRCgl/qAEA7Rzv/ZsGd/R75pqdx3o5RScfFHSXQAyxBwemvhYRI8wCROi8y57PfGNlZojRwjnYrtrX3jrXKTU0QupwhatvBztNNcCdvOYz1G4QJ4LKsmdwWuZ4YVz+GOb0zmh3FtPYqavjDp0iDAvPi2R2j6ACxBW+S8wgS4Q58rEz2HXWEEXBI3GXSNWaRpIfO3G+nxjiyurntHDE1s0WP5012IBHR2ymrNyjhowyVP08GXam9HSJVnmpJ8gzLL9kzgJnTha0koJT1F24salSom69GkQo2iECAnkZ8L0MYvxxeABXoHKDTfegNh9J/5ajlPNDqKcFBKf/qm4sxF4mpHxJQIqXNXgpX3+74/UkyXIVZ49cW/IzapInoCwJsrsEm+3HBNHEZuorJsEnDFtq3u/gRI4rbZ2N31cqVZW5YrZ8y05fU5CQIZM95nf+ILq0HzNyzeJPjFjuNSWjX7y9NZyYdrn8nwOqN12eeN3z1mJ8oIFJ7BogTpE2GmYbPUdwPx6bSYSA3TYIhBbfl/0y1lUuxcpnM/ehTJ+qMygSFJqei5dgFIRdDMTF+u6WDX5lB8Kmmp316dRizprlB+2ecFgS/5pnNGLVRe6GFl/tUWc8Hmc=

